#!/usr/bin/env node
/**
 * Interactive client setup wizard.
 * Generates apps/web/config/branding.ts and apps/web/app/brand.css.
 *
 * Usage: pnpm setup:client
 */

import { createInterface } from "readline/promises";
import { stdin as input, stdout as output } from "process";
import { writeFileSync } from "fs";
import { resolve } from "path";

const ROOT = resolve(__dirname, "..");

const rl = createInterface({ input, output });

async function ask(question: string, defaultValue?: string): Promise<string> {
  const hint = defaultValue ? ` (default: ${defaultValue})` : "";
  const answer = await rl.question(`${question}${hint}: `);
  return answer.trim() || defaultValue || "";
}

function generatePalette(hex: string): Record<string, string> {
  // Simple lightness-based palette generation using the base color
  // In a real project you'd use a library like chroma-js or color2k
  return {
    50: lighten(hex, 0.95),
    100: lighten(hex, 0.9),
    200: lighten(hex, 0.75),
    300: lighten(hex, 0.6),
    400: lighten(hex, 0.4),
    500: lighten(hex, 0.15),
    600: hex,
    700: darken(hex, 0.1),
    800: darken(hex, 0.2),
    900: darken(hex, 0.3),
  };
}

function hexToRgb(hex: string): [number, number, number] {
  const n = parseInt(hex.replace("#", ""), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

function rgbToHex(r: number, g: number, b: number): string {
  return (
    "#" +
    [r, g, b]
      .map((v) => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, "0"))
      .join("")
  );
}

function lighten(hex: string, amount: number): string {
  const [r, g, b] = hexToRgb(hex);
  return rgbToHex(r + (255 - r) * amount, g + (255 - g) * amount, b + (255 - b) * amount);
}

function darken(hex: string, amount: number): string {
  const [r, g, b] = hexToRgb(hex);
  return rgbToHex(r * (1 - amount), g * (1 - amount), b * (1 - amount));
}

async function main() {
  console.log("\n🚀 React Shop — Client Setup Wizard\n");

  const storeName = await ask("Store name", "React Shop");
  const tagline = await ask("Tagline", "Best Online Shopping Experience");
  const description = await ask(
    "Description",
    "Shop the latest products at unbeatable prices."
  );
  const logoAbbrev = await ask("Logo abbreviation (1-2 chars)", storeName[0]?.toUpperCase() ?? "R");
  const logoUrl = await ask("Logo image URL (leave blank for text icon)", "");
  const primaryColor = await ask("Primary brand color (hex)", "#0284c7");
  const supportEmail = await ask("Support email", `support@${storeName.toLowerCase().replace(/\s+/g, "")}.com`);

  rl.close();

  const palette = generatePalette(primaryColor);
  const darkPrimary = lighten(primaryColor, 0.3);

  // ── Write branding.ts ────────────────────────────────────────────────────
  const brandingContent = `// Generated by \`pnpm setup:client\`. Edit directly or re-run to regenerate.
export interface BrandingConfig {
  store: { name: string; tagline: string; description: string; logoText: string; logoAbbrev: string; logoUrl?: string };
  contact: { email: string; phone?: string; address?: string };
  social: { facebook?: string; twitter?: string; instagram?: string };
  features: { newsletter: boolean; reviews: boolean; wishlist: boolean; darkMode: boolean };
  theme: { primaryColor: string; primaryColorDark: string };
}

export const branding: BrandingConfig = {
  store: {
    name: ${JSON.stringify(storeName)},
    tagline: ${JSON.stringify(tagline)},
    description: ${JSON.stringify(description)},
    logoText: ${JSON.stringify(storeName)},
    logoAbbrev: ${JSON.stringify(logoAbbrev.slice(0, 2))},
    ${logoUrl ? `logoUrl: ${JSON.stringify(logoUrl)},` : "// logoUrl: undefined (using text icon)"}
  },
  contact: {
    email: ${JSON.stringify(supportEmail)},
  },
  social: {},
  features: {
    newsletter: true,
    reviews: true,
    wishlist: true,
    darkMode: true,
  },
  theme: {
    primaryColor: ${JSON.stringify(primaryColor)},
    primaryColorDark: ${JSON.stringify(darkPrimary)},
  },
};
`;

  // ── Write brand.css ──────────────────────────────────────────────────────
  const cssContent = `/*
 * Client branding overrides — generated by \`pnpm setup:client\`.
 * Edit directly or re-run setup:client to regenerate.
 */

:root {
  --color-primary:     ${palette[600]};
  --color-primary-50:  ${palette[50]};
  --color-primary-100: ${palette[100]};
  --color-primary-200: ${palette[200]};
  --color-primary-300: ${palette[300]};
  --color-primary-400: ${palette[400]};
  --color-primary-500: ${palette[500]};
  --color-primary-600: ${palette[600]};
  --color-primary-700: ${palette[700]};
  --color-primary-800: ${palette[800]};
  --color-primary-900: ${palette[900]};
}

.dark {
  color-scheme: dark;
  --color-primary:     ${darkPrimary};
  --color-primary-500: ${lighten(primaryColor, 0.25)};
  --color-primary-600: ${lighten(primaryColor, 0.15)};
  --color-primary-700: ${primaryColor};
}
`;

  // ── Write .env ───────────────────────────────────────────────────────────
  const envContent = `NEXT_PUBLIC_API_URL=http://localhost:5001
NEXT_PUBLIC_STORE_NAME=${JSON.stringify(storeName)}
NEXT_PUBLIC_STORE_TAGLINE=${JSON.stringify(tagline)}
NEXT_PUBLIC_STORE_DESCRIPTION=${JSON.stringify(description)}
NEXT_PUBLIC_LOGO_ABBREV=${JSON.stringify(logoAbbrev.slice(0, 2))}
NEXT_PUBLIC_LOGO_URL=${JSON.stringify(logoUrl)}
NEXT_PUBLIC_PRIMARY_COLOR=${JSON.stringify(primaryColor)}
`;

  const brandingPath = resolve(ROOT, "apps/web/config/branding.ts");
  const cssPath = resolve(ROOT, "apps/web/app/brand.css");
  const envPath = resolve(ROOT, "apps/web/.env.local");

  writeFileSync(brandingPath, brandingContent);
  writeFileSync(cssPath, cssContent);
  writeFileSync(envPath, envContent);

  console.log(`\n✅ Done!\n`);
  console.log(`  ${brandingPath}`);
  console.log(`  ${cssPath}`);
  console.log(`  ${envPath}`);
  console.log(`\nRestart your dev server to pick up the changes.\n`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
